<?php

namespace Database\Seeders;

use App\Models\Medicine;
use App\Models\MedicinePurchase;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class MedicineSeeder extends Seeder
{
    public function run(): void
    {
        // Nonaktifkan foreign key checks agar aman di MySQL production saat reset data
        Schema::disableForeignKeyConstraints();

        MedicinePurchase::query()->delete();
        Medicine::query()->delete();

        Schema::enableForeignKeyConstraints();

        $medicines = [
            // ================= HALAMAN 2 =================
            [
                'nama' => 'SIDAMETHRIN 100 ml',
                'jenis' => 'Insektisida',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Ulat grayak (Spodoptera litura), wereng daun, belalang, perusak daun',
                'tanaman_sasaran' => 'Cabai, Bawang Merah, Tomat, Jagung, Kedelai',
                'dosis_anjuran' => '1 - 2 ml / liter air',
                'interval_aplikasi' => 'Setiap 5 - 7 hari saat serangan hama muncul',
                'harga' => 22000,
                'unsur_bahan' => 'Sipermetrin 50 g/l (Cypermethrin)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Gunakan masker dan sarung tangan saat aplikasi, berbahaya bagi lebah madu.',
                'keterangan' => 'Insektisida sintetik piretroid racun kontak dan lambung berspektrum luas dengan efek melumpuhkan yang cepat.',
                'tanggal_beli' => '2026-08-10',
                'toko_obat' => 'Toko Tani Subur Makmur',
            ],
            [
                'nama' => 'BESVIDAN 100 ml',
                'jenis' => 'Insektisida',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Wereng coklat, kutu daun (aphids), kutu kebul, thrips',
                'tanaman_sasaran' => 'Padi, Cabai, Tomat, Terung, Melon',
                'dosis_anjuran' => '0.75 - 1 ml / liter air',
                'interval_aplikasi' => 'Setiap 7 hari sekali secara preventif atau kuratif',
                'harga' => 35000,
                'unsur_bahan' => 'Imidakloprid 25% SL (Imidacloprid)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Racun sistemik, simpan di tempat sejuk dan terkunci jauh dari jangkauan anak.',
                'keterangan' => 'Insektisida sistemik neonikotinoid yang cepat diserap tanaman untuk melindungi dari hama penusuk dan pengisap.',
                'tanggal_beli' => '2026-08-12',
                'toko_obat' => 'Kios Pertanian Tani Jaya',
            ],
            [
                'nama' => 'DECIS 100 ml',
                'jenis' => 'Insektisida',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Ulat grayak, kutu daun, pengorok daun, lalat buah, belalang',
                'tanaman_sasaran' => 'Cabai, Tomat, Bawang Merah, Kentang, Kubis, Jagung',
                'dosis_anjuran' => '1 - 1.5 ml / liter air (15-20 ml / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 5 - 7 hari bila ditemukan hama',
                'harga' => 38000,
                'unsur_bahan' => 'Deltametrin 25 g/l (Deltamethrin)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Daya knock-down sangat kuat, hindari terkena mata dan kulit langsung.',
                'keterangan' => 'Insektisida kontak dan lambung berkualitas tinggi produksi Bayer dengan efek knock-down cepat dan sifat penolak hama.',
                'tanggal_beli' => '2026-08-15',
                'toko_obat' => 'Kios Sahabat Petani',
            ],
            [
                'nama' => 'NPK 16-16-16 MUTIARA',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Pemenuhan nutrisi makro primer berimbang fase awal vegetatif, anakan, dan tunas',
                'tanaman_sasaran' => 'Cabai, Bawang Merah, Tomat, Padi, Jagung, Semangka',
                'dosis_anjuran' => '10 gram / liter air (kocor 200 ml/tanaman) atau 5-10 gram tabur/tanaman',
                'interval_aplikasi' => 'Setiap 7 - 10 hari sekali',
                'harga' => 18000,
                'unsur_bahan' => 'Nitrogen (N) 16%, Fosfat (P2O5) 16%, Kalium (K2O) 16%, CaO, MgO',
                'fase' => 'Vegetatif',
                'catatan_keamanan' => 'Larutkan dengan air bersih, jangan mengenai langsung batang muda saat penaburan.',
                'keterangan' => 'Pupuk majemuk seimbang berbentuk prill biru cepat larut dari YARA/Meroke untuk merangsang akar, batang kokoh, dan pertunasan.',
                'tanggal_beli' => '2026-08-18',
                'toko_obat' => 'Toko Pupuk Makmur Abadi',
            ],
            [
                'nama' => 'KALSIUM CALHA 1 kg',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Mencegah rontok bunga & buah, busuk pantat buah (blossom end rot), layu pucuk',
                'tanaman_sasaran' => 'Cabai, Tomat, Melon, Semangka, Terung',
                'dosis_anjuran' => '2 - 3 gram / liter air (semprot) atau 5 gram / liter air (kocor)',
                'interval_aplikasi' => 'Setiap 7 hari sekali',
                'harga' => 25000,
                'unsur_bahan' => 'CaCO3 90%, Asam Humat 7%, Boron (B) & Seng (Zn)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Kompatibel dicampur pestisida non-alkalis, aduk rata sebelum dimasukkan tangki.',
                'keterangan' => 'Pupuk kalsium murni berpartikel halus plus asam humat dan hara mikro untuk menguatkan dinding sel dan daya tahan penyakit.',
                'tanggal_beli' => '2026-08-20',
                'toko_obat' => 'Sentra Tani Mandiri',
            ],
            [
                'nama' => 'ASAM HUMAT POWER SOIL 500 gram',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Pembenah tanah, menetralkan keasaman tanah, penstimulasi pertumbuhan akar muda',
                'tanaman_sasaran' => 'Semua Tanaman Hortikultura dan Pangan',
                'dosis_anjuran' => '2 gram / liter air (kocor ke lubang tanam)',
                'interval_aplikasi' => 'Setiap 10 - 14 hari',
                'harga' => 35000,
                'unsur_bahan' => 'Asam Humat (Humic Acid) 85%, Kalium (K2O) 10%',
                'fase' => 'Vegetatif',
                'catatan_keamanan' => 'Organik ramah lingkungan, larutkan dalam wadah terpisah terlebih dahulu.',
                'keterangan' => 'Kondisioner tanah konsentrasi tinggi untuk mengembalikan kegemburan tanah rusak dan meningkatkan KTK (Kapasitas Tukar Kation).',
                'tanggal_beli' => '2026-08-22',
                'toko_obat' => 'Toko Tani Subur Makmur',
            ],
            [
                'nama' => 'ASAM HUMAT POWER SOIL 1 kg',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Pembenah struktur tanah olahan, pengikat residu pupuk kimia, memacu mikroba tanah',
                'tanaman_sasaran' => 'Semua Tanaman Pertanian, Perkebunan, dan Sayuran',
                'dosis_anjuran' => '2 gram / liter air (kocor) atau 1 kg campur 100 kg pupuk dasar',
                'interval_aplikasi' => 'Saat olah lahan dasar dan fase awal pertumbuhan',
                'harga' => 65000,
                'unsur_bahan' => 'Asam Humat (Humic Acid) 85%, Kalium (K2O) 10%',
                'fase' => 'Vegetatif',
                'catatan_keamanan' => 'Simpan di tempat teduh dan kering dalam wadah tertutup rapat agar tidak menggumpal.',
                'keterangan' => 'Kemasan hemat 1 kg asam humat murni untuk pemupukan dasar lahan bedengan luas dan optimalisasi serapan pupuk anorganik.',
                'tanggal_beli' => '2026-08-22',
                'toko_obat' => 'Toko Tani Subur Makmur',
            ],
            [
                'nama' => 'AMBITION 500 ml',
                'jenis' => 'Vitamin',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Anti-stres cuaca ekstrem, pindah tanam, pulih overdosis obat, memacu klorofil daun',
                'tanaman_sasaran' => 'Cabai, Padi, Bawang Merah, Tomat, Jagung, Melon',
                'dosis_anjuran' => '1 - 2 ml / liter air (semprot kabut rata pada daun)',
                'interval_aplikasi' => 'Setiap 7 - 10 hari',
                'harga' => 125000,
                'unsur_bahan' => 'Asam Amino 46.9%, Asam Fulvat 2.0%, Unsur Mikro (Zn, B, Mn)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Aman dicampur pupuk daun maupun pestisida non-alkalis.',
                'keterangan' => 'Zat aktivator tanaman produksi Bayer berbahan dasar asam amino esensial lengkap untuk pemulihan cepat dan peningkatan vigor.',
                'tanggal_beli' => '2026-08-25',
                'toko_obat' => 'Kios Agrotani Sejahtera',
            ],
            [
                'nama' => 'PEGASUS 80 ml',
                'jenis' => 'Insektisida',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Tungau merah/kuning (Tetranychus sp.), kutu kebul (Bemisia tabaci), kutu daun',
                'tanaman_sasaran' => 'Cabai, Tomat, Bawang Merah, Semangka, Jeruk',
                'dosis_anjuran' => '1 ml / liter air (15-16 ml / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 5 - 7 hari saat tampak populasi tungau / kutu kebul',
                'harga' => 130000,
                'unsur_bahan' => 'Diafentiuron 500 g/l',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Akarisida spesialis, semprotkan merata terutama pada bagian bawah permukaan daun.',
                'keterangan' => 'Insektisida dan akarisida kontak pernafasan lambung produksi Syngenta ampuh membasmi tungau dan kutu kebul resisten.',
                'tanggal_beli' => '2026-08-27',
                'toko_obat' => 'Sentra Tani Mandiri',
            ],
            [
                'nama' => 'ABACEL 250 ml',
                'jenis' => 'Insektisida',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Thrips (Thrips parvispinus), pengorok daun (Liriomyza sp.), kutu daun',
                'tanaman_sasaran' => 'Cabai, Bawang Merah, Tomat, Mentimun, Padi',
                'dosis_anjuran' => '0.5 - 1 ml / liter air (10-15 ml / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 5 - 7 hari sekali',
                'harga' => 65000,
                'unsur_bahan' => 'Abamektin 18 g/l (Abamectin)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Bekerja secara kontak dan translaminar, jangan gunakan terus menerus tanpa rotasi.',
                'keterangan' => 'Insektisida racun kontak dan lambung dengan penetrasi translaminar tinggi ke dalam jaringan daun membasmi hama tersembunyi.',
                'tanggal_beli' => '2026-08-28',
                'toko_obat' => 'Kios Pertanian Barokah',
            ],
            [
                'nama' => 'BULDOK 100 ml',
                'jenis' => 'Insektisida',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Ulat grayak, ulat penggerek tongkol jagung, belalang, kutu daun',
                'tanaman_sasaran' => 'Jagung, Cabai, Kedelai, Kapas, Tembakau',
                'dosis_anjuran' => '1 - 1.5 ml / liter air',
                'interval_aplikasi' => 'Setiap 5 - 7 hari saat ada serangan',
                'harga' => 38000,
                'unsur_bahan' => 'Beta-siflutrin 25 g/l (Beta-cyfluthrin)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Semprot pagi atau sore hari saat angin tenang, gunakan pelindung muka.',
                'keterangan' => 'Insektisida sintetik piretroid Bayer berdaya knock-down ekstra cepat membungkam ulat grayak dan belalang.',
                'tanggal_beli' => '2026-08-29',
                'toko_obat' => 'Kios Sahabat Petani',
            ],
            [
                'nama' => 'GANDASIL D 500 gram',
                'jenis' => 'Vitamin',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Memacu pertumbuhan daun, tunas baru, klorofil, dan memperkokoh tanaman muda',
                'tanaman_sasaran' => 'Sayuran Daun, Cabai, Bawang Merah, Padi, Jagung, Tanaman Hias',
                'dosis_anjuran' => '2 - 3 gram / liter air (20-30 gram / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 7 - 10 hari',
                'harga' => 35000,
                'unsur_bahan' => 'Nitrogen (N) 20%, Fosfat (P2O5) 15%, Kalium (K2O) 15% + Mikro (Mg, Mn, B, Cu, Co, Zn)',
                'fase' => 'Vegetatif',
                'catatan_keamanan' => 'Larut sempurna dalam air, jangan disemprot pada siang hari saat matahari terik.',
                'keterangan' => 'Pupuk daun legendaris nutrisi makro mikro lengkap khusus fase vegetatif untuk daun lebih lebat, hijau, dan sehat.',
                'tanggal_beli' => '2026-08-30',
                'toko_obat' => 'Toko Tani Subur Makmur',
            ],

            // ================= HALAMAN 3 =================
            [
                'nama' => 'VICTORY 1 kg',
                'jenis' => 'Fungisida',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Busuk daun (Phytophthora infestans), bercak ungu (Alternaria porri), patek antraknosa',
                'tanaman_sasaran' => 'Bawang Merah, Cabai, Kentang, Tomat, Semangka',
                'dosis_anjuran' => '2 - 3 gram / liter air (semprot rata pada daun dan batang)',
                'interval_aplikasi' => 'Setiap 5 - 7 hari terutama pada musim hujan lebat',
                'harga' => 85000,
                'unsur_bahan' => 'Mankozeb 80% (Formula Tepung Kuning WP)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Fungisida protektif kontak, gunakan masker saat menimbang tepung.',
                'keterangan' => 'Fungisida kontak spektrum luas berbentuk tepung kuning halus yang membentuk lapisan pelindung anti-jamur di daun.',
                'tanggal_beli' => '2026-09-01',
                'toko_obat' => 'Sentra Tani Mandiri',
            ],
            [
                'nama' => 'GRAMOXON / Curah Biru',
                'jenis' => 'Perlengkapan',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Gulma berdaun lebar, gulma berdaun sempit, rumput teki saat olah tanah',
                'tanaman_sasaran' => 'Persiapan Lahan Tanaman Pangan, Hortikultura, dan Perkebunan',
                'dosis_anjuran' => '5 - 10 ml / liter air (semprot langsung ke gulma aktif)',
                'interval_aplikasi' => '1 kali aplikasi saat persiapan/pembersihan lahan sebelum tanam',
                'harga' => 75000,
                'unsur_bahan' => 'Parakuat diklorida 276 g/l (Herbisida Kontak)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'AWAS RACUN KERAS! Hindari semprotan mengenai tanaman pokok, gunakan APD lengkap.',
                'keterangan' => 'Herbisida kontak purna tumbuh membakar habis bagian hijau rumput liar dalam hitungan jam untuk mempercepat olah tanah.',
                'tanggal_beli' => '2026-09-01',
                'toko_obat' => 'Kios Pertanian Barokah',
            ],
            [
                'nama' => 'CURACARON 500 ml',
                'jenis' => 'Insektisida',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Ulat grayak (Spodoptera litura), ulat buah (Helicoverpa armigera), kutu daun, trips',
                'tanaman_sasaran' => 'Cabai, Bawang Merah, Tomat, Kubis, Kapas',
                'dosis_anjuran' => '1 - 2 ml / liter air (15-25 ml / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 5 - 7 hari',
                'harga' => 135000,
                'unsur_bahan' => 'Profenofos 500 g/l (Curacron 500 EC)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Berbau khas menyengat, berdaya translaminar dan membunuh telur ulat (efek ovisida).',
                'keterangan' => 'Insektisida racun kontak dan lambung berspektrum luas dari Syngenta andalan petani untuk menuntaskan ulat membandel.',
                'tanggal_beli' => '2026-09-02',
                'toko_obat' => 'Toko Tani Subur Makmur',
            ],
            [
                'nama' => 'LIONTIN PEREKAT',
                'jenis' => 'Perlengkapan',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Memaksimalkan penyerapan pestisida, merekatkan larutan semprot di daun berlilin saat hujan',
                'tanaman_sasaran' => 'Semua Tanaman Pertanian dan Sayuran',
                'dosis_anjuran' => '0.5 - 1 ml / liter air (10-15 ml / tangki 16 L)',
                'interval_aplikasi' => 'Dicampurkan bersama pestisida atau pupuk daun setiap kali penyemprotan',
                'harga' => 25000,
                'unsur_bahan' => 'Alkilaril poliglikol eter (Surfaktan non-ionik)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Campurkan paling terakhir ke dalam tangki setelah obat dan pupuk teraduk rata.',
                'keterangan' => 'Bahan perata, perekat, dan penembus kualitas tinggi mencegah larutan pestisida tercuci air hujan atau jatuh dari daun berlilin.',
                'tanggal_beli' => '2026-09-02',
                'toko_obat' => 'Kios Sahabat Petani',
            ],
            [
                'nama' => 'ANTRACOL 500 gram',
                'jenis' => 'Fungisida',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Antraknosa (patek), busuk daun (Phytophthora), bercak ungu, karat daun',
                'tanaman_sasaran' => 'Cabai, Tomat, Bawang Merah, Padi, Semangka, Melon',
                'dosis_anjuran' => '2 gram / liter air (30 gram / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 7 hari sekali',
                'harga' => 80000,
                'unsur_bahan' => 'Propineb 70% + Seng (Zinc 15.8%)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Aman untuk tunas muda, memberikan pasokan unsur seng yang menyuburkan daun.',
                'keterangan' => 'Fungisida kontak protektif nomor satu produksi Bayer yang melindungi tanaman dari jamur sekaligus memberi efek menyehatkan daun.',
                'tanggal_beli' => '2026-09-03',
                'toko_obat' => 'Kios Pertanian Tani Jaya',
            ],
            [
                'nama' => 'ANTRACOL 250 gram',
                'jenis' => 'Fungisida',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Pencegahan bercak ungu pada daun bawang, busuk daun tomat/cabai, patek',
                'tanaman_sasaran' => 'Cabai, Tomat, Bawang Merah, Kentang, Padi',
                'dosis_anjuran' => '2 gram / liter air (30 gram / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 7 hari sekali',
                'harga' => 45000,
                'unsur_bahan' => 'Propineb 70% + Zinc',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Gunakan masker penutup hidung saat menuangkan tepung.',
                'keterangan' => 'Kemasan ekonomis 250 gram Antracol Bayer untuk skala kebun sedang dan perlindungan tanaman hortikultura.',
                'tanggal_beli' => '2026-09-03',
                'toko_obat' => 'Kios Pertanian Tani Jaya',
            ],
            [
                'nama' => 'NPK GROWER KCRN',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Pengisian dan pembesaran buah, peningkatan bobot panen, pencegahan rontok buah',
                'tanaman_sasaran' => 'Cabai, Tomat, Bawang Merah, Melon, Semangka, Jeruk',
                'dosis_anjuran' => '10 - 15 gram / liter air (kocor 250 ml/tanaman) atau 15-20 gram tabur/tanaman',
                'interval_aplikasi' => 'Setiap 7 - 10 hari pada masa pembungaan dan pengisian buah',
                'harga' => 20000,
                'unsur_bahan' => 'Nitrogen (N) 15%, Fosfat (P2O5) 9%, Kalium (K2O) 20% + Trace Elements (YaraMila/KCRN)',
                'fase' => 'Generatif',
                'catatan_keamanan' => 'Sangat cepat larut, tabur dengan jarak 10-15 cm dari pangkal batang utama.',
                'keterangan' => 'Pupuk majemuk kalium tinggi khusus fase generatif untuk mendongkrak bobot panen, kekerasan daging buah, dan rasa manis.',
                'tanggal_beli' => '2026-09-04',
                'toko_obat' => 'Toko Pupuk Makmur Abadi',
            ],
            [
                'nama' => 'GANDASIL B 500 gram',
                'jenis' => 'Vitamin',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Merangsang pembungaan serentak, mencegah rontok putik/pentil, memperbesar buah',
                'tanaman_sasaran' => 'Cabai, Tomat, Padi, Semangka, Melon, Bawang Merah',
                'dosis_anjuran' => '2 - 3 gram / liter air (semprot daun merata di pagi hari)',
                'interval_aplikasi' => 'Setiap 7 - 10 hari sekali pada fase generatif',
                'harga' => 38000,
                'unsur_bahan' => 'Nitrogen (N) 6%, Fosfor (P2O5) 20%, Kalium (K2O) 30% + Mikro (Mg, Mn, B, Cu, Zn)',
                'fase' => 'Generatif',
                'catatan_keamanan' => 'Hindari semprotan berlebih tepat saat bunga mekar penuh agar lebah penyerbuk tidak terganggu.',
                'keterangan' => 'Pupuk daun khusus pembuahan formula fosfor kalium tinggi untuk hasil panen melimpah berbobot mantap.',
                'tanggal_beli' => '2026-09-04',
                'toko_obat' => 'Toko Tani Subur Makmur',
            ],
            [
                'nama' => 'PREVATON 250 ml',
                'jenis' => 'Insektisida',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Ulat grayak (Spodoptera frugiperda/litura), penggerek batang (sundep/beluk), ulat buah',
                'tanaman_sasaran' => 'Padi, Jagung, Cabai, Bawang Merah, Kubis',
                'dosis_anjuran' => '1.5 - 2 ml / liter air (20-30 ml / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 7 - 10 hari',
                'harga' => 165000,
                'unsur_bahan' => 'Klorantraniliprol 50 g/l (Chlorantraniliprole)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Sangat ramah musuh alami, bekerja meresap melindungi tunas baru dari dalam.',
                'keterangan' => 'Insektisida sistemik premium FMC menghentikan aktivitas makan ulat dalam beberapa menit dan melumpuhkan secara permanen.',
                'tanggal_beli' => '2026-09-05',
                'toko_obat' => 'Sentra Tani Mandiri',
            ],
            [
                'nama' => 'AMISTARTOP 100 ml',
                'jenis' => 'Fungisida',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Blas padi (Pyricularia oryzae), patek antraknosa, hawar pelepah, bercak kering',
                'tanaman_sasaran' => 'Padi, Cabai, Bawang Merah, Tomat, Jagung',
                'dosis_anjuran' => '0.5 - 1 ml / liter air (10-15 ml / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 7 - 10 hari',
                'harga' => 95000,
                'unsur_bahan' => 'Azoksistrobin 200 g/l + Difenokonazol 125 g/l',
                'fase' => 'Generatif',
                'catatan_keamanan' => 'Mengandung zat pengatur tumbuh (ZPT) yang membuat tanaman hijau segar dan bulir padat.',
                'keterangan' => 'Fungisida sistemik ganda spektrum luas Syngenta dengan teknologi ZPT memaksimalkan bobot gabah dan kualitas panen buah.',
                'tanggal_beli' => '2026-09-05',
                'toko_obat' => 'Kios Agrotani Sejahtera',
            ],
            [
                'nama' => 'NPK DGW ARJUAN / POSKA',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Pemupukan dasar dan susulan awal memacu kesuburan anakan dan daun hijau',
                'tanaman_sasaran' => 'Padi Sawah, Jagung, Hortikultura, Perkebunan',
                'dosis_anjuran' => '150 - 250 kg / hektar (atau kocor 10 gram / liter air)',
                'interval_aplikasi' => 'Saat olah lahan dasar dan umur 15-20 HST',
                'harga' => 12000,
                'unsur_bahan' => 'Nitrogen 15%, Fosfat 15%, Kalium 15% + Sulfur (S) & Seng (Zn)',
                'fase' => 'Vegetatif',
                'catatan_keamanan' => 'Simpan di gudang beralaskan palet kayu agar butiran pupuk tetap kering.',
                'keterangan' => 'Pupuk majemuk NPK seimbang diperkaya sulfur dan zinc untuk fondasi pertumbuhan vegetatif yang kuat dan produktif.',
                'tanggal_beli' => '2026-09-06',
                'toko_obat' => 'Toko Pupuk Makmur Abadi',
            ],
            [
                'nama' => 'TALI CAP BEL GOLONG BESAR',
                'jenis' => 'Perlengkapan',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Pengikat ajir lanjaran dan penopang cabang tanaman berbuah lebat agar tidak patah/rebah',
                'tanaman_sasaran' => 'Cabai, Tomat, Melon, Mentimun, Buncis, Pare',
                'dosis_anjuran' => 'Sesuai kebutuhan bentangan lanjaran (gulungan besar ±1000 meter)',
                'interval_aplikasi' => 'Dipasang saat tiang ajir berdiri pada umur 15-20 HST',
                'harga' => 35000,
                'unsur_bahan' => 'Polypropylene (PP) Anti-UV Tahan Cuaca Panas & Hujan',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Bahan kuat tidak melukai kulit batang tanaman yang sedang berkembang.',
                'keterangan' => 'Tali salaran cap Bel gulungan besar berserat padat tahan radiasi UV matahari dan tidak mudah putus ditiup angin kencang.',
                'tanggal_beli' => '2026-09-06',
                'toko_obat' => 'Kios Sahabat Petani',
            ],
            [
                'nama' => 'TALI CAP BEL GOLONG KECIL',
                'jenis' => 'Perlengkapan',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Pengikat percabangan tanaman dan sulur rambatan ke tiang ajir',
                'tanaman_sasaran' => 'Cabai, Tomat, Mentimun, Buncis, Kacang Panjang',
                'dosis_anjuran' => 'Sesuai kebutuhan bentangan bedengan (gulungan kecil ±400 meter)',
                'interval_aplikasi' => 'Dipasang saat fase percabangan aktif',
                'harga' => 18000,
                'unsur_bahan' => 'Polypropylene (PP) Anti-UV',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Praktis dan mudah diikatkan dengan simpul hidup.',
                'keterangan' => 'Tali salaran cap Bel gulungan kecil ekonomis untuk penataan tajuk dan cabang buah agar tertata rapi.',
                'tanggal_beli' => '2026-09-06',
                'toko_obat' => 'Kios Sahabat Petani',
            ],
            [
                'nama' => 'BIBIT BUNCIS MERK LEBAT 500 gram',
                'jenis' => 'Bibit',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Benih buncis unggul tahan karat daun dengan produksi polong lebat dan lurus',
                'tanaman_sasaran' => 'Budidaya Tanaman Buncis',
                'dosis_anjuran' => '15 - 20 kg benih per hektar (1-2 biji per lubang tanam)',
                'interval_aplikasi' => 'Ditanam langsung saat hari tanam (0 HST)',
                'harga' => 55000,
                'unsur_bahan' => 'Benih Buncis Lebat Unggul (Daya berkecambah min 85%, kemurnian 98%)',
                'fase' => 'Vegetatif',
                'catatan_keamanan' => 'Rendam air hangat 15 menit sebelum ditanam untuk mempercepat pecah kecambah.',
                'keterangan' => 'Benih buncis bersertifikasi resmi tipe tegak/merambat dengan polong lentur hijau segar renyah bernilai jual tinggi.',
                'tanggal_beli' => '2026-09-07',
                'toko_obat' => 'Toko Tani Subur Makmur',
            ],
            [
                'nama' => 'ZA',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Pembentukan zat hijau daun klorofil, meningkatkan aroma tajam umbi dan ketahanan penyakit',
                'tanaman_sasaran' => 'Bawang Merah, Bawang Putih, Cabai, Tebu, Tembakau',
                'dosis_anjuran' => '5 - 10 gram / liter air (kocor) atau 100 - 150 kg / hektar (tabur)',
                'interval_aplikasi' => 'Diberikan pada umur 10 - 25 HST',
                'harga' => 8000,
                'unsur_bahan' => 'Nitrogen (N) 21%, Belerang / Sulfur (S) 24%',
                'fase' => 'Vegetatif',
                'catatan_keamanan' => 'Pupuk bersifat masam, perhatikan pH tanah sebelum pengaplikasian dosis tinggi.',
                'keterangan' => 'Pupuk amonium sulfat Zwavelzure Amoniak sumber hara belerang dan nitrogen tinggi untuk kekenyalan dan kualitas umbi.',
                'tanggal_beli' => '2026-09-07',
                'toko_obat' => 'Toko Pupuk Makmur Abadi',
            ],
            [
                'nama' => 'COPCIDE 400 gram',
                'jenis' => 'Fungisida',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Bakteri busuk basah (Erwinia), hawar daun bakteri (kresek), patek antraknosa',
                'tanaman_sasaran' => 'Cabai, Tomat, Padi, Kentang, Jeruk',
                'dosis_anjuran' => '1.5 - 2 gram / liter air (25-30 gram / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 5 - 7 hari terutama saat kondisi lembap',
                'harga' => 75000,
                'unsur_bahan' => 'Tembaga Hidroksida (Copper Hydroxide) 77% (setara Cu 50%)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Bakterisida kontak kuat, jangan dicampur fosfat asam pekat dalam satu wadah.',
                'keterangan' => 'Bakterisida dan fungisida tembaga modern mikro partikel sangat halus dan melekat kuat mengendalikan bakteri & cendawan.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Sentra Tani Mandiri',
            ],
            [
                'nama' => 'COPCIDE 1 kg',
                'jenis' => 'Fungisida',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Pengendalian bakteri Xanthomonas oryzae, busuk buah berair, dan kanker batang',
                'tanaman_sasaran' => 'Padi, Cabai, Tomat, Jeruk, Kakao',
                'dosis_anjuran' => '1.5 - 2 gram / liter air (25-30 gram / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 7 hari sekali',
                'harga' => 165000,
                'unsur_bahan' => 'Tembaga Hidroksida (Copper Hydroxide) 77%',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Gunakan kacamata dan sarung tangan saat pengadukan larutan pekat.',
                'keterangan' => 'Kemasan 1 kg hemat untuk lahan sawah dan hortikultura luas melawan serangan bakteri busuk basah dan hawar pelepah.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Sentra Tani Mandiri',
            ],
            [
                'nama' => 'BIBIT BONTENG MERK SEMI F1',
                'jenis' => 'Bibit',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Benih mentimun hibrida unggul tahan Gemini virus (virus kuning) dan embun tepung',
                'tanaman_sasaran' => 'Budidaya Mentimun / Bonteng',
                'dosis_anjuran' => '800 - 1000 gram benih per hektar (1 biji per lubang tanam)',
                'interval_aplikasi' => 'Ditanam saat hari penanaman (0 HST)',
                'harga' => 45000,
                'unsur_bahan' => 'Benih Mentimun Hibrida F1 Semi (Daya kecambah 90%, kemurnian 99%)',
                'fase' => 'Vegetatif',
                'catatan_keamanan' => 'Simpan benih yang belum dipakai pada wadah kedap di tempat sejuk terlindung matahari.',
                'keterangan' => 'Benih mentimun hibrida produktivitas tinggi dengan buah silindris hijau mulus, renyah tanpa rasa pahit disukai pasar.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Toko Tani Subur Makmur',
            ],
            [
                'nama' => 'DOLOMIT',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Menaikkan derajat keasaman (pH) tanah, menetralkan keracunan Al/Fe, suplai Ca & Mg',
                'tanaman_sasaran' => 'Semua Lahan Budidaya Hortikultura, Padi, dan Sayuran',
                'dosis_anjuran' => '1 - 2 ton / hektar (atau 100-200 gram / m2 bedengan)',
                'interval_aplikasi' => '1 kali saat pengolahan tanah 1-2 minggu sebelum pasang mulsa',
                'harga' => 2000,
                'unsur_bahan' => 'Kalsium Oksida (CaO) 30%, Magnesium Oksida (MgO) 20%',
                'fase' => 'Vegetatif',
                'catatan_keamanan' => 'Taburkan secara merata saat tanah dalam kondisi lembap lalu cangkul rata.',
                'keterangan' => 'Kapur pertanian alami sumber kalsium dan magnesium esensial untuk memulihkan tanah masam menjadi subur gembur.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Toko Pupuk Makmur Abadi',
            ],
            [
                'nama' => 'KNO3 KALIUM NITRAT CRYSTAL 1 kg',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Mencegah rontok bunga & putik, memacu pembesaran buah, menambah bobot dan kadar gula',
                'tanaman_sasaran' => 'Cabai, Bawang Merah, Melon, Semangka, Tomat, Jeruk',
                'dosis_anjuran' => '3 - 5 gram / liter air (semprot) atau 5 - 10 gram / liter air (kocor)',
                'interval_aplikasi' => 'Setiap 7 hari pada masa pembungaan dan pembuahan',
                'harga' => 45000,
                'unsur_bahan' => 'Nitrogen Nitrat (N-NO3) 13%, Kalium (K2O) 46% (Kristal Larut 100%)',
                'fase' => 'Generatif',
                'catatan_keamanan' => 'Bebas klorin, tidak membuat tanah masam, aman diaplikasikan semprot maupun kocor.',
                'keterangan' => 'Pupuk kalium nitrat kristal larut 100% tanpa residu cepat diserap tanaman untuk menggenjot bobot dan mutu panen buah.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Sentra Tani Mandiri',
            ],
            [
                'nama' => 'RAPIA GOLONG BESAR',
                'jenis' => 'Perlengkapan',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Tali penarik mulsa plastik bedengan, pengikat ajir bambu, pengikat karung hasil panen',
                'tanaman_sasaran' => 'Perlengkapan Semua Lahan Budidaya Pertanian',
                'dosis_anjuran' => 'Sesuai kebutuhan bentangan lahan dan volume karung panen',
                'interval_aplikasi' => 'Saat persiapan bedengan dan saat pengemasan pasca panen',
                'harga' => 22000,
                'unsur_bahan' => 'Serat Plastik Polimer Sintetik Kuat & Fleksibel',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Tidak beracun, kumpulkan kembali sisa tali rafia agar tidak mencemari tanah.',
                'keterangan' => 'Tali rafia gulungan besar tebal, ulet, dan tidak gampang putus untuk berbagai kebutuhan lapangan budidaya.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Kios Sahabat Petani',
            ],
            [
                'nama' => 'ASAM HUMAT SUPER SOIL 1 kg',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Mengikat residu pupuk kimia, mengaktifkan koloni mikroba tanah, retensi kelembaban',
                'tanaman_sasaran' => 'Cabai, Tomat, Kentang, Bawang Merah, Padi',
                'dosis_anjuran' => '2 - 3 gram / liter air (kocor ke pangkal batang)',
                'interval_aplikasi' => 'Setiap 10 - 14 hari',
                'harga' => 60000,
                'unsur_bahan' => 'Kalium Humat 80%, Asam Fulvat 15%, Unsur Mikro Organik',
                'fase' => 'Vegetatif',
                'catatan_keamanan' => 'Dapat dicampur bersama pupuk NPK kocor untuk meningkatkan efisiensi hara.',
                'keterangan' => 'Pembenah biologi tanah berkadar asam fulvat tinggi yang mengoptimalkan daya serap hara pada perakaran tanaman.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Kios Pertanian Tani Jaya',
            ],
            [
                'nama' => 'MKP SU PA TANI',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Merangsang inisiasi bunga serentak, mencegah rontok putik, memperkokoh tangkai buah',
                'tanaman_sasaran' => 'Cabai, Tomat, Melon, Semangka, Kentang, Anggur',
                'dosis_anjuran' => '2 - 4 gram / liter air (semprot) atau 5 - 10 gram / liter air (kocor)',
                'interval_aplikasi' => 'Setiap 7 hari sejak keluar bakal kuncup bunga',
                'harga' => 48000,
                'unsur_bahan' => 'Fosfat (P2O5) 52%, Kalium (K2O) 34% (Mono Kalium Fosfat Bebas N)',
                'fase' => 'Generatif',
                'catatan_keamanan' => 'Bentuk kristal putih larut 100%, hindari pencampuran dengan kalsium pekat.',
                'keterangan' => 'Pupuk pembuahan mono kalium fosfat standar Pak Tani yang memacu tanaman berbunga lebat dan buah padat berisi.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Toko Tani Subur Makmur',
            ],
            [
                'nama' => 'TRICODERMA GLIO TRICO 500 gram',
                'jenis' => 'Fungisida',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Layu Fusarium (Fusarium oxysporum), layu bakteri, busuk pangkal batang tular tanah',
                'tanaman_sasaran' => 'Cabai, Tomat, Terung, Bawang Merah, Semangka, Pepaya',
                'dosis_anjuran' => '5 - 10 gram / liter air (kocor lubang tanam) atau 1 kg campur 100 kg kompos',
                'interval_aplikasi' => 'Saat olah lahan dasar dan diulang pada umur 15 & 30 HST',
                'harga' => 35000,
                'unsur_bahan' => 'Trichoderma harzianum & Gliocladium sp. 10^7 spora/gram',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Agens hayati hidup, jangan dicampur bersamaan dengan fungisida kimia sintetis.',
                'keterangan' => 'Biofungisida hayati jamur antagonis pemangsa spora pathogen tular tanah penyebab penyakit layu kuning dan rebah bibit.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Sentra Tani Mandiri',
            ],
            [
                'nama' => 'KARUNG WARING',
                'jenis' => 'Perlengkapan',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Wadah pengepakan panen hasil bumi agar tidak busuk/pengap selama transportasi',
                'tanaman_sasaran' => 'Panen Cabai Merah, Cabai Rawit, Tomat, Sayur Mayur',
                'dosis_anjuran' => '1 karung kapasitas 25 - 50 kg hasil panen',
                'interval_aplikasi' => 'Digunakan saat panen petik buah',
                'harga' => 3500,
                'unsur_bahan' => 'Anyaman Plastik Polipropilena Berpori Ventilasi Udara',
                'fase' => 'Generatif',
                'catatan_keamanan' => 'Bersihkan dan keringkan setelah pakai agar awet digunakan berulang kali.',
                'keterangan' => 'Karung jaring waring merah/hitam dengan lubang sirkulasi udara menjaga kesegaran cabai dan tomat hingga ke pasar.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Kios Sahabat Petani',
            ],
            [
                'nama' => 'HIDRO KARATE BORON',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Mencegah kerontokan bunga, mencegah ujung buah busuk / retak, menguatkan tangkai',
                'tanaman_sasaran' => 'Cabai, Tomat, Semangka, Melon, Mangga, Jeruk',
                'dosis_anjuran' => '10 - 15 gram per tanaman (tabur / kocor 5 gram/liter)',
                'interval_aplikasi' => 'Setiap 10 - 14 hari pada fase generatif',
                'harga' => 22000,
                'unsur_bahan' => 'Nitrogen Nitrat (N-NO3) 15.4%, Kalsium Oksida (CaO) 25.6%, Boron (B) 0.3%',
                'fase' => 'Generatif',
                'catatan_keamanan' => 'Pupuk larut sempurna dari Yara, kombinasi kalsium nitrat dan boron murni.',
                'keterangan' => 'Pupuk kalsium nitrat plus boron YaraMila untuk mencegah buah pecah, memperpanjang daya simpan, dan mempertebal kulit buah.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Toko Pupuk Makmur Abadi',
            ],
            [
                'nama' => 'MAESTRO 500 ml',
                'jenis' => 'Fungisida',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Bercak daun (Cercospora), patek antraknosa (Colletotrichum), busuk buah, karat daun',
                'tanaman_sasaran' => 'Cabai, Bawang Merah, Padi, Kedelai, Tomat',
                'dosis_anjuran' => '0.5 - 1 ml / liter air (10-15 ml / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 7 hari sekali',
                'harga' => 78000,
                'unsur_bahan' => 'Difenokonazol 200 g/l (Difenoconazole)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Bekerja preventif dan kuratif menghentikan infeksi jamur dari dalam jaringan.',
                'keterangan' => 'Fungisida sistemik golongan triazol berdaya serap cepat melindungi jaringan tanaman dari dalam terhadap serangan jamur.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Kios Pertanian Tani Jaya',
            ],
            [
                'nama' => 'EMACEL 500 ml',
                'jenis' => 'Insektisida',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Ulat grayak (Spodoptera exigua/litura), pengorok daun (Liriomyza), ulat penggerek',
                'tanaman_sasaran' => 'Bawang Merah, Cabai, Kubis, Tomat, Jagung',
                'dosis_anjuran' => '0.5 - 1 ml / liter air (8-15 ml / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 5 - 7 hari bila ulat aktif menyerang',
                'harga' => 85000,
                'unsur_bahan' => 'Emamektin Benzoat 30 g/l (Emamectin Benzoate)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Melumpuhkan syaraf ulat dengan dosis rendah, jangan disemprot dekat sumber air ikan.',
                'keterangan' => 'Insektisida kontak lambung spesialis membasmi ulat grayak bawang merah dan cabai yang sudah kebal racun kimia umum.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Sentra Tani Mandiri',
            ],
            [
                'nama' => 'CARBIOTOP 500 gram',
                'jenis' => 'Fungisida',
                'cara_kerja' => 'Sistemik + Kontak',
                'sasaran_obat' => 'Antraknosa patek, busuk daun Phytophthora, bercak kering Alternaria',
                'tanaman_sasaran' => 'Cabai, Tomat, Bawang Merah, Kentang, Semangka',
                'dosis_anjuran' => '1.5 - 2 gram / liter air (25-30 gram / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 7 hari sekali',
                'harga' => 140000,
                'unsur_bahan' => 'Metiram 55% + Piraklostrobin 5% (Fungisida BASF AgCelence)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Dua kombinasi bahan aktif kontak dan sistemik, semprot menyeluruh.',
                'keterangan' => 'Fungisida sistemik kontak protektif dan kuratif berteknologi AgCelence membuat daun hijau kokoh dan terbebas dari patek.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Toko Tani Subur Makmur',
            ],
            [
                'nama' => 'BIO SIGMA PLUS - TRICHODERMA',
                'jenis' => 'Fungisida',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Penyakit tular tanah, layu fusarium, rebah kecambah, busuk perakaran',
                'tanaman_sasaran' => 'Semua Tanaman Hortikultura dan Palawija',
                'dosis_anjuran' => '5 gram / liter air (kocor ke media tanam / lubang tanam)',
                'interval_aplikasi' => 'Saat persemaian dan pindah tanam',
                'harga' => 40000,
                'unsur_bahan' => 'Isolat Trichoderma viride + Mikoriza + Bakteri Pelarut Fosfat',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Biofungisida hayati ramah lingkungan, jangan dicampur bakterisida kimia.',
                'keterangan' => 'Agens biologis hayati proteksi akar dan perangsang kesuburan mikroba baik dalam zona perakaran tanaman.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Kios Agrotani Sejahtera',
            ],
            [
                'nama' => 'NORDOX',
                'jenis' => 'Fungisida',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Hawar daun bakteri (kresek), busuk basah buah, cacar daun, antraknosa',
                'tanaman_sasaran' => 'Padi, Cabai, Kakao, Kopi, Jeruk, Bawang Merah',
                'dosis_anjuran' => '1 - 2 gram / liter air (15-30 gram / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 7 hari sekali',
                'harga' => 55000,
                'unsur_bahan' => 'Tembaga Oksida (Cu2O) 56% (setara Cu 50%)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Formula tepung merah mikro melekat sangat kuat, tahan guyuran hujan deras.',
                'keterangan' => 'Fungisida dan bakterisida kontak alami tembaga merah protektif nomor satu di Indonesia untuk penyakit bakteri dan jamur.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Sentra Tani Mandiri',
            ],

            // ================= HALAMAN 4 =================
            [
                'nama' => 'AVIDOR 100 gram',
                'jenis' => 'Insektisida',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Wereng coklat, wereng hijau, kutu daun (Aphids), thrips, kutu kebul',
                'tanaman_sasaran' => 'Padi, Cabai, Bawang Merah, Tomat, Semangka',
                'dosis_anjuran' => '0.5 - 1 gram / liter air (10-15 gram / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 7 hari sekali',
                'harga' => 28000,
                'unsur_bahan' => 'Imidakloprid 25% WP (Imidacloprid)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Bekerja sistemik diserap daun dan akar melindungi tanaman dari dalam.',
                'keterangan' => 'Insektisida sistemik tepung putih cepat larut menghentikan hama wereng dan mencegah penularan virus daun keriting.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Kios Sahabat Petani',
            ],
            [
                'nama' => 'HIDRO KARATE KCRN',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Memperkuat dinding sel, mencegah busuk ujung batang, meningkatkan daya tahan penyakit',
                'tanaman_sasaran' => 'Cabai, Tomat, Kentang, Bawang Merah, Melon',
                'dosis_anjuran' => '10 - 15 gram / liter air (kocor) atau 10-20 gram / tanaman (tabur)',
                'interval_aplikasi' => 'Setiap 7 - 10 hari',
                'harga' => 18000,
                'unsur_bahan' => 'Nitrogen Nitrat (N-NO3) 15.5%, Kalsium Oksida (CaO) 26%',
                'fase' => 'Vegetatif',
                'catatan_keamanan' => 'Kalsium nitrat larut 100%, hindari pencampuran dengan sulfat konsentrasi tinggi.',
                'keterangan' => 'Pupuk kalsium nitrat murni untuk pertumbuhan struktur sel tanaman kokoh, tidak mudah rebah dan bebas busuk pucuk.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Toko Pupuk Makmur Abadi',
            ],
            [
                'nama' => 'KCL KCRN',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Pengisian bulir, pembesaran umbi bawang dan buah cabai, peningkatan daya simpan panen',
                'tanaman_sasaran' => 'Padi, Jagung, Cabai, Bawang Merah, Kentang, Kelapa Sawit',
                'dosis_anjuran' => '100 - 150 kg / hektar (atau kocor 10 gram / liter air)',
                'interval_aplikasi' => 'Diberikan pada fase generatif saat pembentukan buah dan umbi',
                'harga' => 14000,
                'unsur_bahan' => 'Kalium Klorida (K2O 60%) Formula KCRN / Mahkota',
                'fase' => 'Generatif',
                'catatan_keamanan' => 'Mengandung klorida, aplikasikan saat kondisi tanah cukup lembab.',
                'keterangan' => 'Pupuk kalium tunggal konsentrasi tinggi 60% K2O untuk mendongkrak bobot panen, kekerasan buah, dan ketahanan simpan.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Toko Pupuk Makmur Abadi',
            ],
            [
                'nama' => 'DITHANE 1 kg',
                'jenis' => 'Fungisida',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Busuk daun (Phytophthora infestans), antraknosa, bercak kering (Alternaria solani)',
                'tanaman_sasaran' => 'Kentang, Tomat, Cabai, Bawang Merah, Kedelai',
                'dosis_anjuran' => '2 - 3 gram / liter air (30-40 gram / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 5 - 7 hari terutama pada musim penghujan',
                'harga' => 145000,
                'unsur_bahan' => 'Mankozeb 80% (Dithane M-45 80 WP Kuning)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Fungisida kontak protektif berstandar internasional, pakai masker saat menuang.',
                'keterangan' => 'Fungisida kontak legendaris Corteva berspektrum luas untuk perlindungan total tanaman dari infeksi spora cendawan.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Sentra Tani Mandiri',
            ],
            [
                'nama' => 'FITOFLEK SACHET',
                'jenis' => 'Vitamin',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Mencegah klorosis daun kuning, mengatasi defisiensi hara mikro, aktivasi enzim sel',
                'tanaman_sasaran' => 'Semua Tanaman Pertanian, Sayuran, dan Buah',
                'dosis_anjuran' => '1 sachet (2.5 gram) per tangki 16 liter air',
                'interval_aplikasi' => 'Setiap 10 - 14 hari sekali',
                'harga' => 8000,
                'unsur_bahan' => 'Unsur Mikro Kelat EDTA (Fe, Zn, Mn, Cu, B, Mo) Lengkap',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Bentuk kelat EDTA stabil dan cepat diserap jaringan tanaman.',
                'keterangan' => 'Pupuk mikro majemuk berkepekatan tinggi dalam kemasan sachet praktis untuk menjaga kesuburan dan daun tetap hijau sehat.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Toko Tani Subur Makmur',
            ],
            [
                'nama' => 'KNO3 PUTIH PAK TANI',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Mempercepat pembungaan, mencegah rontok buah, meningkatkan rasa manis dan bobot panen',
                'tanaman_sasaran' => 'Cabai, Melon, Semangka, Tomat, Bawang Merah, Kentang',
                'dosis_anjuran' => '3 - 5 gram / liter air (semprot) atau 10 gram / liter air (kocor)',
                'interval_aplikasi' => 'Setiap 7 hari saat mulai berbunga hingga pembesaran buah',
                'harga' => 45000,
                'unsur_bahan' => 'Nitrogen Nitrat (N-NO3) 13%, Kalium (K2O) 45% (Bebas Klorin)',
                'fase' => 'Generatif',
                'catatan_keamanan' => 'Pupuk murni higienis larut 100% tanpa residu endapan.',
                'keterangan' => 'Pupuk kalium nitrat putih Pak Tani pilihan utama petani untuk menghasilkan buah berbobot kelas satu dengan rasa manis alami.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Toko Tani Subur Makmur',
            ],
            [
                'nama' => 'KNO3 MERAH PAK TANI',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Mempercepat pertumbuhan tunas baru, anakan batang, dan perakaran kuat awal tanam',
                'tanaman_sasaran' => 'Cabai, Bawang Merah, Padi, Jagung, Semangka',
                'dosis_anjuran' => '5 - 10 gram / liter air (kocor) atau 10 - 20 gram tabur/tanaman',
                'interval_aplikasi' => 'Setiap 7 - 10 hari pada fase awal tanam',
                'harga' => 42000,
                'unsur_bahan' => 'Nitrogen (N) 15%, Kalium (K2O) 15%, Natrium (Na) 18% (Formula C-Prill)',
                'fase' => 'Vegetatif',
                'catatan_keamanan' => 'Tidak menyebabkan tanah masam, ramah lingkungan dan cepat meresap.',
                'keterangan' => 'Pupuk kalium nitrat merah Pak Tani khusus fase awal vegetatif memacu pertumbuhan anakan dan batang tanaman muda yang kokoh.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Toko Tani Subur Makmur',
            ],
            [
                'nama' => 'ATONIK',
                'jenis' => 'Vitamin',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Merangsang perakaran stek/semai, memulihkan tanaman stres, memacu penyerbukan',
                'tanaman_sasaran' => 'Padi, Cabai, Bawang Merah, Tomat, Kentang, Kedelai',
                'dosis_anjuran' => '1 ml / liter air (15-20 ml / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 7 - 10 hari',
                'harga' => 45000,
                'unsur_bahan' => 'Natrium para-nitrofenolat, Natrium orto-nitrofenolat, Natrium 5-nitrogaiakolat (ZPT Atonik)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Dapat dicampur dengan semua jenis pestisida dan pupuk daun.',
                'keterangan' => 'Zat Pengatur Tumbuh (ZPT) legendaris dari Asahi Jepang untuk memperlancar sirkulasi protoplasma sel dan memacu daya hidup tanaman.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Kios Agrotani Sejahtera',
            ],
            [
                'nama' => 'ULTRADAP PAK TANI',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Merangsang perakaran cepat, anakan produktif, dan inisiasi pembentukan bunga',
                'tanaman_sasaran' => 'Cabai, Tomat, Padi, Jagung, Kentang, Semangka',
                'dosis_anjuran' => '2 - 4 gram / liter air (semprot) atau 5 - 10 gram / liter air (kocor)',
                'interval_aplikasi' => 'Setiap 7 hari pada umur 7 - 35 HST',
                'harga' => 48000,
                'unsur_bahan' => 'Nitrogen (N) 12%, Fosfat (P2O5) 60% (Mono Ammonium Phosphate MAP)',
                'fase' => 'Vegetatif',
                'catatan_keamanan' => 'Kandungan fosfat 60% larut air sempurna, sangat cepat diserap oleh akar muda.',
                'keterangan' => 'Pupuk mono ammonium phosphate andalan Pak Tani untuk mempercepat perkembangan akar primer sekunder dan pembentukan bunga.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Toko Tani Subur Makmur',
            ],
            [
                'nama' => 'MATADOR',
                'jenis' => 'Insektisida',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Ulat grayak, ulat buah, wereng hijau, kepik, belalang, lalat bibit',
                'tanaman_sasaran' => 'Cabai, Padi, Bawang Merah, Jagung, Kapas',
                'dosis_anjuran' => '1 - 2 ml / liter air (15-25 ml / tangki 16 L)',
                'interval_aplikasi' => 'Setiap 5 - 7 hari',
                'harga' => 35000,
                'unsur_bahan' => 'Lamda-sihalotrin 25 g/l (Lambda-cyhalothrin)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Racun kontak dan lambung berefek repellent menolak hama datang kembali.',
                'keterangan' => 'Insektisida sintetik piretroid produksi Syngenta berdaya knock-down cepat dan bertahan lama melindungi daun.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Kios Pertanian Tani Jaya',
            ],
            [
                'nama' => 'M-21',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Dekomposisi cepat kotoran hewan/jerami, mematikan bibit patogen tanah, hilangkan bau',
                'tanaman_sasaran' => 'Olah Lahan Pertanian, Pembuatan Kompos & Fermentasi Kohe',
                'dosis_anjuran' => '2 - 5 ml / liter air (semprot ke bahan organik / lahan sebelum mulsa)',
                'interval_aplikasi' => '1 kali saat pembuatan kompos atau 7 hari sebelum tanam',
                'harga' => 55000,
                'unsur_bahan' => 'Konsorsium Mikroba Dekomposer (Trichoderma, Actinomycetes, Lactobacillus, Streptomyces)',
                'fase' => 'Vegetatif',
                'catatan_keamanan' => 'Dekomposer biologi ramah lingkungan, simpan di tempat sejuk terlindung matahari.',
                'keterangan' => 'Formula bakteri pengurai modern untuk mempercepat fermentasi pupuk kandang menjadi kompos matang kaya nutrisi.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Kios Agrotani Sejahtera',
            ],
            [
                'nama' => 'MALIKA',
                'jenis' => 'Bibit',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Benih kedelai hitam polong lebat, tahan kekeringan dan tahan penyakit karat daun',
                'tanaman_sasaran' => 'Budidaya Tanaman Kedelai Hitam',
                'dosis_anjuran' => '40 - 50 kg benih per hektar (2-3 biji per lubang tanam)',
                'interval_aplikasi' => 'Ditanam saat awal hari tanam (0 HST)',
                'harga' => 35000,
                'unsur_bahan' => 'Benih Kedelai Hitam Unggul Malika (Daya kecambah min 85%, kemurnian 98%)',
                'fase' => 'Vegetatif',
                'catatan_keamanan' => 'Simpan di ruangan berventilasi kering agar daya viabilitas biji tetap terjaga.',
                'keterangan' => 'Benih kedelai hitam unggulan bersertifikat resmi bahan baku kecap premium dengan potensi panen tinggi.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Toko Tani Subur Makmur',
            ],
            [
                'nama' => 'MANCOZEB',
                'jenis' => 'Fungisida',
                'cara_kerja' => 'Kontak',
                'sasaran_obat' => 'Bercak daun cercospora, patek antraknosa, busuk daun phytophthora, karat daun',
                'tanaman_sasaran' => 'Cabai, Bawang Merah, Kentang, Tomat, Semangka, Melinjo',
                'dosis_anjuran' => '2 - 3 gram / liter air (semprot merata permukaan daun)',
                'interval_aplikasi' => 'Setiap 5 - 7 hari',
                'harga' => 75000,
                'unsur_bahan' => 'Mankozeb 80% WP (Tepung Biru / Kuning)',
                'fase' => 'Semua Fase',
                'catatan_keamanan' => 'Fungisida multi-site tidak mudah menyebabkan jamur menjadi resisten.',
                'keterangan' => 'Fungisida protektif serbaguna pengendali penyakit jamur tular udara pada tanaman hortikultura dan pangan.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Sentra Tani Mandiri',
            ],
            [
                'nama' => 'NITREA',
                'jenis' => 'Pupuk',
                'cara_kerja' => 'Sistemik',
                'sasaran_obat' => 'Memacu pertumbuhan vegetatif daun, batang, anakan padi, dan pembentukan klorofil',
                'tanaman_sasaran' => 'Padi, Jagung, Tebu, Hortikultura, Perkebunan',
                'dosis_anjuran' => '100 - 200 kg / hektar (atau kocor 5 gram / liter air)',
                'interval_aplikasi' => 'Diberikan pada umur 7 - 14 HST dan 25 - 30 HST',
                'harga' => 12000,
                'unsur_bahan' => 'Nitrogen (N) 46% (Pupuk Urea Nitrea Prill Pupuk Kujang / Pupuk Indonesia)',
                'fase' => 'Vegetatif',
                'catatan_keamanan' => 'Larut sangat cepat, tutup kembali karung dengan rapat karena sifatnya higroskopis.',
                'keterangan' => 'Pupuk urea nitrogen konsentrasi tinggi 46% butiran prill putih tidak berdebu untuk pertumbuhan vegetatif daun dan batang hijau royo-royo.',
                'tanggal_beli' => '2026-09-08',
                'toko_obat' => 'Toko Pupuk Makmur Abadi',
            ],
        ];

        foreach ($medicines as $item) {
            $medicine = Medicine::create($item);

            // Buat record pembelian awal di medicine_purchases
            if ($item['toko_obat'] || $item['harga'] || $item['tanggal_beli']) {
                MedicinePurchase::create([
                    'medicine_id' => $medicine->id,
                    'toko_obat' => $item['toko_obat'],
                    'harga' => $item['harga'],
                    'tanggal_beli' => $item['tanggal_beli'],
                    'catatan' => 'Pembelian awal inventaris '.$item['nama'],
                ]);
            }
        }
    }
}
