name: Deploy to Hostinger

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USER }}
        key: ${{ secrets.HOSTINGER_SSH }}
        port: ${{ secrets.HOSTINGER_PORT }}
        script: |
          cd ${{ secrets.HOSTINGER_PATH }}
          # Cek apakah folder sudah git repository
          if [ ! -d .git ]; then
            git init
            git remote add origin https://github.com/zullpy/agritrack.git
          fi
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan optimize:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache